language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: QW52MvPepsVNmY8Vdfd1xATb94YexNpboES5xdcMK1RP4KmykyDgvtyGiqDyi1mlgsfA4LEqn+N2/CPio1g9UFjISx9REuFt/nENb8NbgRgaeBc7hHMhe1oIhKZspJCA9DDW0df7hy1eS6zI2WpWtA4hV0D8EJ9yu/6uWPPBjvWSHj0ApJ4PGdqeEQ1/I8C2qZNa+rSkkv4skhWG+OlJZYWKjGYldSUYE6NTCjGi18BVMSSSI7RlXYza+7CHYRnsERY2rJkwjpVlEJz5c0Oa59mGxPmmoUKojUpxUyB7ZTcI794Ark9akZwXZSO/fbXWx1bOJUbBQpOh8COu+RqDHCx/32cK9mN8aUfeJJgra8M6jQfwQ6QK7Aohz8TnH1nBJ3Uac7H1QdlPaoQwH/9kXAOscs5DfhJMnSxu1pHuD2KCl4ga7mrZOwab1/ufZzPivw6fT9Drp6BbQvgDPX7RAokvnrsV/f+wj4GjSarPefsNQaTmIfy9dDMxi1XXnV1jpzc/7Tk61lc1jj/UL9Nu3ivdi1myGnsRW1R7saLIdGjDikykUfM6juOSFs/63IAdMlKlK1Z9mTbQbaWNlfA/PbvT7fppJudAiDRfEwsDtqS7UnAc/g80ot988YJ6eWkY+5rczn6fSKoA9MoQp9fHE1fWMJuA2s44e0yT8+huZg4=
  app: projet-adavid
  on: 
repo: adavid1/projet
