language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: nBqUg04B/SSaZDCqCDlkQlUm/yYLef4eAomR+i+7KyFsiHNMoigoLdND0YFgnYw5fReOgGFEuBcFSJqkUnG9fH/ZIItOoeiuaKV6VgoNYluMax9/mj1fhuPMcItqvkEXipNueQM56Ft4OtdkXZgzAPoqUwStnP92dk6OgTZXur/ebE8gZnI4h7pFElLKChze3fHVx3RpOm30xCSU+ijv5eJtHMLzVRcUsMirVFcR9IYzzOZP7/umOCvSeQFCG9Fr0gWpR4Yh5RcQpXyzDxs8JXhixOBkBGtV1jx3YBq66hdyHIA7apXtShzd+u055YWyD2SGc+lirqLPemFBhUA/M8+zSi4PEFXyfVoa/Oq0WF7v4/OHJ5F+2IS58q/n0nKQ9uEQvvL5qsCwXagMGwskwwvb76sA/ziePwzJr32QEhJVAyygdOSc4MOzllkacANzxK+vwvrcSG1X+fezXPVbq5dka/+Sl7/HPEc2syowhCAHeF7tbEHoBg88n7fx6ysCc16YPiJxgvzHYCp3pfKAf0ATbG+3A3wXmxStobpKlYf17qON8xef6bOkyVzFM8Lg8HIXM1FnwOfjXjQhxIsn3GOcc+CuDwwhbgyk1Vi+J6WJlZQ9/31bk7NL+T5S35jlMaXNYCGpZT3/pilsZNirBscha4Yu88nG5Ivl1w5Zl9k=
  app: projet1-adavid
  on:
    repo: adavid1/projet
  run : 
- "rake db:drop"
- "rake db:migrate RAILS_ENV=production"
before_script:
- psql -c 'create database travis_ci_test;' -U postgres